#!/usr/bin/env groovy

def sendFailureEmail() {
    def content = "Build for branch ${env.BRANCH_NAME} Failed."
    def info = 'Check the attached log or log into jenkins'
    emailext(
        mimeType: "text/html; charset=UTF-8",
        to: "jcamilodz@gmail.com",
        recipientProviders: [[$class: 'CulpritsRecipientProvider'], [$class: "RequesterRecipientProvider"]],
        body: "${content}<br/>${info}<br/>",
        subject: "Jenkins: Your build ${env.BRANCH_NAME} - Build #${env.BUILD_NUMBER} - Failed!",
        attachLog: true,
        attachmentsPattern: 'reports.zip'
    )
}

node() {
    try{

        
       def ecrUri = "#############"
        
        stage("Clean workspace"){
            cleanWs()
        }

        stage("Setup"){
            checkout scm
        }
        dir("tecnica"){
        stage("Test") {
            withGradle {
                sh './gradlew test'
            }
        }
        stage("Build JAR artifact") {
            withGradle {
                sh './gradlew build'
            }
        }
        stage("Build Docker image"){
            dockerImage = docker.build("${ecrUri}/jcdd/demoback")
        }
        stage("Push Docker image"){
                script {
                sh("aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ecrUri}")
                dockerImage.push('latest')
                }
                
            }


        }
        dir("helm"){
        
        stage("Deploy with Helm"){
            
            sh("echo $HOME")
            sh("kubectl config view --raw")
            sh("cat ~/.kube/config")
            sh("export KUBECONFIG=~/.kube/config")
            sh("whoami")
            sh("sudo su ec2-user && whoami && helm upgrade demoback . -v20")
            
        }
            


        }
    
    
    } catch(error) {
        throw error
		sendFailureEmail()
    } finally {
        cleanWs()
    }
}